author: Serg Hospodarets
keywords: javascript,js,html,html5,css,css3,git,shell,node.js,frontend
personal-site-url: https://hospodarets.com
# Name of site (displayed in the header)
name: Serg Hospodarets Blog
email: shospodarets@gmail.com
FORMSPREE_ACTION: https://formspree.io/f/mbjpnnbr
static-resources-url: /images/img

# Short bio or description (displayed in the header)
description: Front-end web development blog with tutorials and ideas about JavaScript, CSS, HTML and other Web technologies
description_short: Serg Hospodarets blog

#
# Flags below are optional
#

# Web masters verification
web-master-verifications:
  google: K72aDcuBi_K3YZuq5ukJUg4n-m5CRXFrHiwKeoW-AaA
  bing: F619F8324622C7FE081AE7C74E79EC63
  yandex: 73e26d3db8066c7f

# Includes an icon in the footer for each username
social-links:
  linkedin: shospodarets
  github: shospodarets
  rss: hospodarets.com # make sure the "url" above is set!
  feedburner: https://feeds.feedburner.com/hospodarets # RSS alternative subscription
  feedburner_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=hospodarets
  twitter: shospodarets
  codepen: shospodarets
#  facebook: sergeygospodaretsblog

# https://jekyllrb.com/docs/pagination/
paginate: 5

# This will enable commenting on posts
disqus: malyw-github-io

# Google Analytics web tracking code
google_analytics: G-0EKTHCEJ98

# Google custom search ID
google_search: 012363491708652379866:741arfehybe

# Tidio chat
tidio_chat_id: vhbqoafvnrtyspexrbwoacjemwjflyhf

# Website URL
# Used for Sitemap.xml and your RSS feed
url: https://hospodarets.com
urls:
  blog: /
  speaking: /speaking
  about: /about
  contact: /contact
code_base_url: https://github.com/shospodarets/malyw.github.io
demos_code_base_url: https://github.com/shospodarets/malyw.github.io/tree/master/demos
full_base_url: https://hospodarets.com
github_pages_base_url: https://shospodarets.github.io

# If hosting site at a Project repository on GitHub pages
# (https://username.github.io/repository-name)
# and NOT your User repository (https://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
#
#

markdown: kramdown

highlighter: rouge

permalink: /:title

# Exclude these files from production _site
exclude:
    - LICENSE
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules
    - /**/node_modules
    - other
    - npm-debug.log
    - npm-debug.log.*

include:
    # lodash-es/_*.js files for native ECMAScript imports
    - _*.js

# Plugins (gems)
plugins:
  - jekyll
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag
