author: Serg Hospodarets
keywords: javascript,js,html,html5,css,css3,git,shell,node.js,frontend
personal-site-url: https://hospodarets.com
google-plus-account-url: https://plus.google.com/u/0/111936785055168982101
google-plus-posts: https://plus.google.com/u/0/111936785055168982101/posts
# Name of site (displayed in the header)
name: Serg Hospodarets Blog
email: shospodarets@gmail.com
CONTACT_EMAIL: shospodarets

# Short bio or description (displayed in the header)
description: A front end web development blog with tutorials and ideas about JavaScript, AngularJS, jQuery, CSS, CSS3 and HTML, HTML5
description_short: A front end web development blog

#
# Flags below are optional
#

# Web masters verification
web-master-verifications:
  google: 7cCa3PUlThC4fbmii_QaCaQclo2nB5_d4b4vbhZrL4I
  bing: 464A77B6880D4837BA420DEDB2D9CFF7
  yandex: 66d8056d3b1e88fd

# Includes an icon in the footer for each username
social-links:
  linkedin: malyw
  github: malyw
  rss: hospodarets.com # make sure the "url" above is set!
  feedburner: https://feeds.feedburner.com/hospodarets # RSS alternative subscription
  feedburner_email_subscription: https://feedburner.google.com/fb/a/mailverify?uri=hospodarets
  twitter: malyw
  codepen: malyw
#  facebook: sergeygospodaretsblog
#  googleplus: SergeyGospodarets

# https://jekyllrb.com/docs/pagination/
paginate: 5

# This will enable commenting on posts
disqus: malyw-github-io

# Google Analytics web tracking code
google_analytics: UA-53471595-1

# Google custom search ID
google_search: 012363491708652379866:741arfehybe

# Website URL
# Used for Sitemap.xml and your RSS feed
url: https://hospodarets.com
urls:
  blog: /
  speaking: /speaking
  code-review: /code-review
  about: /about
  contact: /contact
code_base_url: https://github.com/malyw/hospodarets.com
demos_code_base_url: https://github.com/malyw/hospodarets.com/tree/master/demos
full_base_url: https://hospodarets.com

# If hosting site at a Project repository on GitHub pages
# (https://username.github.io/repository-name)
# and NOT your User repository (https://username.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
#
#

markdown: kramdown

highlighter: rouge

permalink: /:title

# Exclude these files from production _site
exclude:
    - LICENSE
    - README.md
    - Gruntfile.js
    - package.json
    - node_modules
    - /**/node_modules
    - other
    - npm-debug.log
    - npm-debug.log.*

include:
    # lodash-es/_*.js files for native ECMAScript imports
    - _*.js

# Gems
gems:
  - jekyll
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - pygments.rb

# Tagging
tag_page_layout: tag_page
tag_page_dir: tag